/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildRouteImport } from './routes/build'
import { Route as GetRouteImport } from './routes/get'
import { Route as MonsterRouteImport } from './routes/monster'
import { Route as MonstersRouteImport } from './routes/monsters'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const GetRoute = GetRouteImport.update({
  id: '/get',
  path: '/get',
  getParentRoute: () => rootRouteImport,
} as any)
const MonsterRoute = MonsterRouteImport.update({
  id: '/monster',
  path: '/monster',
  getParentRoute: () => rootRouteImport,
} as any)
const MonstersRoute = MonstersRouteImport.update({
  id: '/monsters',
  path: '/monsters',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/get': typeof GetRoute
  '/monster': typeof MonsterRoute
  '/monsters': typeof MonstersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/get': typeof GetRoute
  '/monster': typeof MonsterRoute
  '/monsters': typeof MonstersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/get': typeof GetRoute
  '/monster': typeof MonsterRoute
  '/monsters': typeof MonstersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/build' | '/get' | '/monster' | '/monsters'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/build' | '/get' | '/monster' | '/monsters'
  id: '__root__' | '/' | '/build' | '/get' | '/monster' | '/monsters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildRoute: typeof BuildRoute
  GetRoute: typeof GetRoute
  MonsterRoute: typeof MonsterRoute
  MonstersRoute: typeof MonstersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get': {
      id: '/get'
      path: '/get'
      fullPath: '/get'
      preLoaderRoute: typeof GetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monster': {
      id: '/monster'
      path: '/monster'
      fullPath: '/monster'
      preLoaderRoute: typeof MonsterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monsters': {
      id: '/monsters'
      path: '/monsters'
      fullPath: '/monsters'
      preLoaderRoute: typeof MonstersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildRoute: BuildRoute,
  GetRoute: GetRoute,
  MonsterRoute: MonsterRoute,
  MonstersRoute: MonstersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
